### ISSUE TITLE
What is the DTAP? DATP?

### ISSUE THREAD

**Issue by kisec** [FalconForceTeam/FalconFriday#2]
I searched DTAP in "microsoft-azure-strategy-and-implementation-guide"
The guide was written that DTAP is Development, Testing, Acceptance, Production. 
Is it Right?

And DATP was written Defender Advanced Threat Protection.

DTAP and DATP are mixed and written in Readme.
So I am confused. Please explain.😂

**Comment by 0xffhh** [comment]
Kisec, you're our hero! Thank you for pointing out this typo. I've fixed this typo immediately. 

Obviously, we as hackers stay away from DTAP - that's something for developers. We meant to say DATP - Defender Advanced Threat Protection.

Unfortunately, also this name is by now outdated, as the platform now is called "MDE - Microsoft Defender for Endpoint". In the next round of updates, we might replace DATP by MDE. 

Have a great day.
